import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [state, setState] = useState({ title: '', price: '', about: '', image: '' })
  const handleSearch = async (e) => {
    e.preventDefault()
    const { value } = e.target
    const url = `https://amazon-finder.vercel.app/api/hello?url=${value}`
    const { data } = await axios.get(url);
    setState(data)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form className={styles.form}>
          <input onChange={handleSearch} type="text" placeholder="Search" />
        </form>
        <ul>
          <li>
            <Image src={state.image} alt={state.title} width={200} height={200} />
          </li>
          <li>{state.title}</li>
          <li>{state.price}</li>
          <li>{state.about}</li>
        </ul>
      </main>
    </>
  )
}
